# JDBC povezava na PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/heroes_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=5

# Logiranje
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

#Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port
server.port=8080